### ISSUE TITLE
setmirror错误

### ISSUE THREAD

**Issue by Jeta1me1PLUS** [sunoru/PkgMirrors.jl#11]
ERROR: failed process: Process(`'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe' -Version 3 -NoProfile -Command "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; (New-Object System.Net.Webclient).DownloadFile('https://mirrors.ustc.edu.cn/julia/registries/list.txt', 'C:\Users\ytru\.juliapro\JuliaPro_v1.1.0.1\packages\PkgMirrors\N6z12\src\../cache\registries.txt')"`, ProcessExited(1)) [1] Stacktrace:  [1] pipeline_error at .\process.jl:785 [inlined]  [2] download(::String, ::String) at .\download.jl:20  [3] download_cache at C:\Users\ytru\.juliapro\JuliaPro_v1.1.0.1\packages\PkgMirrors\N6z12\src\utils.jl:45 [inlined]  [4] get_registry_list(::String, ::Bool) at C:\Users\ytru\.juliapro\JuliaPro_v1.1.0.1\packages\PkgMirrors\N6z12\src\pkg.jl:13  [5] activate() at C:\Users\ytru\.juliapro\JuliaPro_v1.1.0.1\packages\PkgMirrors\N6z12\src\pkg.jl:23  [6] setmirror(::String, ::String) at C:\Users\ytru\.juliapro\JuliaPro_v1.1.0.1\packages\PkgMirrors\N6z12\src\api.jl:13  [7] setmirror(::String) at C:\Users\ytru\.juliapro\JuliaPro_v1.1.0.1\packages\PkgMirrors\N6z12\src\api.jl:25  [8] top-level scope at none:0

**Comment by sunoru** [comment]
我也看不出是什么错……
手动开一个 Powershell，然后用这个命令试试看？
`[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; (New-Object System.Net.Webclient).DownloadFile('https://mirrors.ustc.edu.cn/julia/registries/list.txt', 'C:\Users\ytru\.juliapro\JuliaPro_v1.1.0.1\packages\PkgMirrors\N6z12\src\../cache\registries.txt')`

**Comment by sunoru** [comment]
I’m closing this issue because it has been inactive for a few months.
