### ISSUE TITLE
循环报错

### ISSUE THREAD

**Issue by N5N3** [sunoru/PkgMirrors.jl#12]
使用报错
ERROR: LoadError: MethodError: no method matching iterate(::typeof(Pkg.Types.DEFAULT_REGISTRIES))
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:568
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:568
  iterate(::ExponentialBackOff) at error.jl:199
  ...
Stacktrace:
 [1] activate() at C:\Users\ad\.juliapro\JuliaPro_v1.1.1.1\packages\PkgMirrors\r65Gt\src\pkg.jl:26
 [2] setmirror(::String, ::String) at C:\Users\ad\.juliapro\JuliaPro_v1.1.1.1\packages\PkgMirrors\r65Gt\src\api.jl:13
 [3] setmirror(::String) at C:\Users\ad\.juliapro\JuliaPro_v1.1.1.1\packages\PkgMirrors\r65Gt\src\api.jl:25
 [4] top-level scope at none:0
in expression starting at C:\Users\ad\.juliapro\JuliaPro_v1.1.1.1\packages\PkgMirrors\r65Gt\test\runtests.jl:11

**Comment by sunoru** [comment]
似乎是 `Pkg.jl` 版本不兼容的问题。。你能把 `versioninfo()` 的输出结果给我看一下吗

**Comment by N5N3** [comment]
julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, ivybridge)
Environment:
  JULIA_EDITOR = "D:\JuliaPro\app-1.36.0\atom.exe"  -a
  JULIA_NUM_THREADS = 2
  JULIA_PKG_SERVER = https://pkg.juliacomputing.com/
  JULIA_PKG_TOKEN_PATH = C:\Users\ad.juliapro\token.toml

**Comment by sunoru** [comment]
嗯我自己装了一个 JuliaPro 1.1.1.1 试了一下，原因出在他们改了官方的 Pkg.jl 以用他们自己的服务器来提供软件包，暂时还跟 PkgMirrors.jl 不兼容……现在我建议的解决方法是重新装一个纯净的 Julia 环境（而不是 JuliaPro）来用国内的镜像。
