### ISSUE TITLE
setmirror: MethodError

### ISSUE THREAD

**Issue by A205B064** [sunoru/PkgMirrors.jl#13]
<img width="667" alt="微信截图_20190909201312" src="https://user-images.githubusercontent.com/32934684/64529806-4aed2780-d33e-11e9-8958-d66735209aa9.png">

I'm using JuliaPro.

PkgMirrors was installed via `add https://mirrors.zju.edu.cn/julia/PkgMirrors.jl.git@v1.0.0`.

**Comment by A205B064** [comment]
According to the stacktrace and the description of the MethodError, I added a pair of parenthesis to the end of line 24 in the source file pkg.jl:
```julia
# original
default_list = Pkg.Types.DEFAULT_REGISTRIES

# modified
default_list = Pkg.Types.DEFAULT_REGISTRIES()
```
then it worked as desired.

**Comment by sunoru** [comment]
It's the same case as https://github.com/sunoru/PkgMirrors.jl/issues/12
Thanks for suggesting this workaround. I may release a new version to fix it.
