### ISSUE TITLE
UndefVarError: DEFAULT_REGISTRIES not defined in JuliaPro 1.0.1.1

### ISSUE THREAD

**Issue by daxinnan** [sunoru/PkgMirrors.jl#3]
when using PkgMirrors.setmirror("ZJU")，the error occurs.
I use JuliaPro on super computer server.
julia> PkgMirrors.setmirror("ZJU")
[ Info: Updating mirror information...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     8  100     8    0     0     21      0 --:--:-- --:--:-- --:--:--    21
ERROR: UndefVarError: DEFAULT_REGISTRIES not defined
Stacktrace:
 [1] getproperty at ./sysimg.jl:13 [inlined]
 [2] activate() at /nuist/scratch/linan/lxc/softs/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/PkgMirrors/BlfKW/src/pkg.jl:24
 [3] setmirror(::String, ::String) at /nuist/scratch/linan/lxc/softs/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/PkgMirrors/BlfKW/src/api.jl:13
 [4] setmirror(::String) at /nuist/scratch/linan/lxc/softs/JuliaPro-1.0.1.1/JuliaPro/pkgs-1.0.1.1/packages/PkgMirrors/BlfKW/src/api.jl:25
 [5] top-level scope at none:0
I don't know to ask whom about it is better. that's it.

**Comment by sunoru** [comment]
Hi, can you run `versioninfo()` and show me the output?

**Comment by daxinnan** [comment]
> Hi, can you run `versioninfo()` and show me the output?

Sorry for not seeing your reply. I usually run julia on a Linux server.
`versioninfo()`
`Julia Version 1.0.1`
`Commit 0d713926f8* (2018-09-29 19:05 UTC)`
`Platform Info:`
`  OS: Linux (x86_64-redhat-linux)`
`  CPU: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz`
`  WORD_SIZE: 64`
`  LIBM: libopenlibm`
`  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)`
I just uninstalled the JuliaPro, and run a source julia1.0.1. Things looks better. But the only ZJU's mirrors doesn't synchronize timely, so some packages.jl has to clone from github to local, and this works slowly. Any thing can do for getting better? Thank you.
