### ISSUE TITLE
源的同步频率是多少

### ISSUE THREAD

**Issue by zsz00** [sunoru/PkgMirrors.jl#6]
PkgMirors 里的源的同步频率是多久啊 ?

**Comment by sunoru** [comment]
目前USTC的源同步比较稳定，ZJU的还在调整中所以经常不够新

**Comment by sunoru** [comment]
ZJU 源现在也是一天一同步了。

**Comment by szcf-weiya** [comment]
> ZJU 源现在也是一天一同步了。

刚注意到 ZJU 源已经一个多月没有更新了
![image](https://user-images.githubusercontent.com/13688320/79183401-f534ac80-7e43-11ea-921d-d4ddfc5b890d.png)

**Comment by sunoru** [comment]
> > ZJU 源现在也是一天一同步了。
> 
> 刚注意到 ZJU 源已经一个多月没有更新了
> ![image](https://user-images.githubusercontent.com/13688320/79183401-f534ac80-7e43-11ea-921d-d4ddfc5b890d.png)

ZJU 源的服务器硬盘满了一直挂着……最近由于疫情缘故学校很多事情似乎处理不过来
