### ISSUE TITLE
ZJU 502

### ISSUE THREAD

**Issue by inkydragon** [sunoru/PkgMirrors.jl#7]
![image](https://user-images.githubusercontent.com/5158738/49336551-4d984f00-f63f-11e8-883c-d6c628f3304f.png)

**Comment by dhzzy88** [comment]
我也遇到了相同的问题，使用中国技术大学的会报错

**Comment by inkydragon** [comment]
> 使用中国技术大学的会报错

我用着 USTC 的挺好的，几个版本都没问题。你报的什么错?
log/截图看看。有必要可以开个 issue

**Comment by dhzzy88** [comment]
我使用的机器是linux
系统为elementary OS 0.4.1 Loki
出现截图中的错误，是不是因为系统的原因。
![downloads_012](https://user-images.githubusercontent.com/31563814/51687301-32d5cb80-202d-11e9-984f-4e1999aea451.png)

**Comment by dhzzy88** [comment]
> 我使用的机器是linux
> 系统为elementary OS 0.4.1 Loki
> 出现截图中的错误，是不是因为系统的原因。
> ![downloads_012](https://user-images.githubusercontent.com/31563814/51687301-32d5cb80-202d-11e9-984f-4e1999aea451.png)

我的问题消失了，应该是我之前安装julia的问题，重新安装后正常使用

**Comment by sunoru** [comment]
我检查了一下，这个是 Julia 1.0.2 里引入的一个兼容性问题，我会在 PkgMirrors.jl 下个版本修复（这两天就改好）

ZJU 的 502 问题也已经修复了

**Comment by sunoru** [comment]
在 https://github.com/JuliaLang/METADATA.jl/pull/20941 里修好了。Bug 是只有 Julia 1.1 开始才有的。
