### ISSUE TITLE
ZJU 源 Tarball with dependencies 缺失

### ISSUE THREAD

**Issue by inkydragon** [sunoru/PkgMirrors.jl#8]
[releaseinfo.json](https://mirrors.zju.edu.cn/julia/releases/releaseinfo.json) 里有 `julia-*.*.*-full.tar.gz`
但 [/releases/v1.0/](https://mirrors.zju.edu.cn/julia/releases/v1.0/) 文件夹里没有

缺失的版本
- v1.0.3
- v1.1
- (0.7 确实是 json 里也没有)

[USTC](https://mirrors.ustc.edu.cn/julia/releases/) 的都有

**Comment by sunoru** [comment]
不知道这个问题之前是怎么产生的，不过现在应该已经没问题了。
