### ISSUE TITLE
initialize the mirror by a script

### ISSUE THREAD

**Issue by norci** [sunoru/PkgMirrors.jl#9]
I prefer using Pkg api to initialize the mirror, like this:
```
import Pkg
Pkg.Registry.add(Pkg.RegistrySpec(url="https://mirrors.zju.edu.cn/julia/registries/General.git"))
Pkg.add(Pkg.PackageSpec(url="https://mirrors.zju.edu.cn/julia/PkgMirrors.jl.git", rev="v1.2.0"))
import PkgMirrors
PkgMirrors.setmirror("ZJU")
```
then I can reuse it easily.
Shall we add this method into the doc? thanks.

**Comment by sunoru** [comment]
The way in the doc is just a more user-friendly method to use Pkg API. And it is exactly the same as what you have proposed, I think?

**Comment by norci** [comment]
Yes. I just want to automate this step. see: https://github.com/norci/dockerfiles/blob/master/julia-cuda/startup.jl

**Comment by sunoru** [comment]
OK. It's added to README.
